### PR TITLE
CSUM-705 - prefilling two graphs with one form

### PR DESCRIPTION
**Pull request by cbenavidesdev**
`**READY/HOLD**`
hold...i have a lot of console logs
### Migrations
`YES | NO`
no
### What's this PR do?
`What does this pull request achieve? How does it impact the application.`

not entirely sure if this is what rick wanted...but this auto fills  industry if the major form was submitted and the reverse

### Where should the reviewer start?  
`What piece of the code received the most attention and your reviewer should start by looking at?`

### Steps to Test or Reproduce
`Outline the steps to test or reproduce the PR here.`

example:
```
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

### Impacted Areas in Application
`List general components of the application that this PR will affect:`

### CODE REVIEW

**Review by luisjg — CHANGES_REQUESTED** [review]
Remove console logs

**Review by luisjg — COMMENTED** [review]
This looks good, did you make sure the mobile versions of these vue components had the same functionality?

**Comment by cbenavidesdev** [comment]
It worked on the chrome mobile view, so yes.

**Comment by luisjg** [comment]
There are vue components that are rendered based on what device you have so you might find it fascinating to find that there's a mobile.vue or something filenames in this project that you have to check as well.

**Comment by cbenavidesdev** [comment]
Tested the code on my phone and chrome's mobile view, it seems to have worked. It also seems kinda weird how theres hardly any actions in industry mobile compared to majors mobile component. Nothing stands out to me that I need to fix in the mobile files as the desktop and mobile components data funnels into the shared mobile/desktop major/industry form component anyway.

**Review by luisjg — APPROVED** [review]

**Pull request merged**
